/**
 * <p>
 * Title: Projecto SD</p>
 * <p>
 * Description: Projecto apoio aulas SD</p>
 * <p>
 * Copyright: Copyright (c) 2011</p>
 * <p>
 * Company: UFP </p>
 *
 * @author Rui Moreira
 * @version 2.0
 */
package edu.ufp.inf.sd.rabbitmqservices.projeto.chatgui;

import com.rabbitmq.client.BuiltinExchangeType;
import edu.ufp.inf.sd.rabbitmqservices._04_topics.chatgui.Observer;
import edu.ufp.inf.sd.rabbitmqservices.util.RabbitUtils;

import javax.swing.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author rjm
 */
public class ObserverGuiClient extends JFrame {

    private edu.ufp.inf.sd.rabbitmqservices._04_topics.chatgui.Observer observer;
    private String generalTopic;

    /**
     * Creates new form ChatClientFrame
     *
     * @param args
     */
    public ObserverGuiClient(String args[]) {
        try {
            //1. Create edu.ufp.inf.sd.rabbitmqservices.projeto.jogo.edu.ufp.inf.sd.rabbitmqservices.projeto.jogo.buildings.edu.ufp.inf.sd.rabbitmqservices.projeto.jogo.gui components
            initComponents();
            Logger.getLogger(this.getClass().getName()).log(Level.INFO, " After initComponents()...");

            //initObserver(args);
            RabbitUtils.printArgs(args);

            //Read args passed via shell command
            String host=args[0];
            int port=Integer.parseInt(args[1]);
            String exchangeName=args[2];
            String room=args[3];
            String user=args[4];
            this.generalTopic=args[5];

            //Set username for chatting
            this.jTextFieldUsername.setText(user);

            //2. Create the _05_observer object that manages send/receive of messages to/from rabbitmq
            this.observer=new Observer(null, host, port, "guest", "guest", room, user, this.generalTopic, exchangeName, BuiltinExchangeType.TOPIC, "UTF-8");

        } catch (IOException | TimeoutException e) {
            e.printStackTrace();
        }

        Logger.getLogger(this.getClass().getName()).log(Level.INFO, " After initObserver()...");
    }

    /**
     * Receives notification about the reception of a message, to update the text area.
     */
    public void updateTextArea() {
        this.jTextAreaChatHistory.append(this.observer.getReceivedMessage() + '\n');
    }

    /**
     * Allows sending a message via the _05_observer, to some user or to generalTopic (all).
     * - Send message to general when strFromJTextField = "some message"
     * - Send message to given user when strFromJTextField = "user@some message"
     *
     * @param strFromJTextField
     */
    private void sendMsg(String strFromJTextField) {
        try {
            String userTo="";
            String msg = "";
            int indexAt = strFromJTextField.indexOf("@");
            //If it dos not specify private user (hence its public general)
            if (indexAt==-1){
                userTo="general";
                msg=strFromJTextField;
            } else {
                //Send to specific private user
                userTo=strFromJTextField.substring(0,indexAt);
                msg=strFromJTextField.substring(indexAt+1);
            }
            Logger.getLogger(ObserverGuiClient.class.getName()).log(Level.INFO, "user="+userTo + ", msg="+msg);
            this.observer.sendMessage(msg, userTo);
        } catch (IOException ex) {
            Logger.getLogger(ObserverGuiClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1=new JFileChooser();
        jScrollPane1=new JScrollPane();
        jTextAreaChatHistory=new JTextArea();
        jButtonSend=new JButton();
        jTextFieldMsg=new JTextField();
        jLabelUserID=new JLabel();
        jTextFieldUsername=new JTextField();
        jMenuBar1=new JMenuBar();
        jMenu1=new JMenu();
        jMenuItemExit=new JMenuItem();
        jMenuItemSave=new JMenuItem();
        jMenu2=new JMenu();
        jMenuItemCopy=new JMenuItem();
        jMenuItemPaste=new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jTextAreaChatHistory.setColumns(20);
        jTextAreaChatHistory.setLineWrap(true);
        jTextAreaChatHistory.setRows(5);
        jTextAreaChatHistory.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaChatHistory);

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jTextFieldMsg.setText("msg");
        jTextFieldMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMsgKeyPressed(evt);
            }
        });

        jLabelUserID.setText("User ID");

        jTextFieldUsername.setText("rmoreira");

        jMenu1.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSave);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItemCopy.setText("Copy");
        jMenuItemCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCopyActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCopy);

        jMenuItemPaste.setText("Paste");
        jMenuItemPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPasteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPaste);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        GroupLayout layout=new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabelUserID)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldUsername, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                        .addComponent(jTextFieldMsg, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSend))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 246, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldMsg, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonSend))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelUserID)
                                        .addComponent(jTextFieldUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopyActionPerformed
        // TODO add your handling code here:
        this.jTextAreaChatHistory.selectAll();
        this.jTextAreaChatHistory.copy();
    }//GEN-LAST:event_jMenuItemCopyActionPerformed

    private void jMenuItemPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPasteActionPerformed
        // TODO add your handling code here:
        this.jTextAreaChatHistory.paste();
    }//GEN-LAST:event_jMenuItemPasteActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        String str = this.jTextFieldMsg.getText();
        Logger.getLogger(ObserverGuiClient.class.getName()).log(Level.INFO, "jTextFieldMsg="+str);
        sendMsg(str);
        this.jTextFieldMsg.setText("");
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jTextFieldMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMsgKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (c == '\n' || c == '\r') {
            String str = this.jTextFieldMsg.getText();
            Logger.getLogger(ObserverGuiClient.class.getName()).log(Level.INFO, "jTextFieldMsg="+str);
            sendMsg(str);
            this.jTextFieldMsg.setText("");
        }
    }//GEN-LAST:event_jTextFieldMsgKeyPressed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        // TODO add your handling code here:
        FileWriter fw=null;
        try {
            this.jFileChooser1=new JFileChooser(new File("C:\\Temp"));
            this.jFileChooser1.showSaveDialog(this);
            File f=this.jFileChooser1.getSelectedFile();
            if (f != null) {
                fw=new FileWriter(f);
                PrintWriter pw=new PrintWriter(fw);
                pw.println(this.jTextAreaChatHistory.getText());
            }
        } catch (IOException ex) {
            Logger.getLogger(ObserverGuiClient.class.getName()).log(Level.SEVERE, ex.toString());
        } finally {
            try {
                if (fw != null) {
                    fw.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(ObserverGuiClient.class.getName()).log(Level.SEVERE, ex.toString());
            }
        }
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (args.length >= 6) {
                    new ObserverGuiClient(args).setVisible(true);
                } else {
                    Logger.getLogger(ObserverGuiClient.class.getName()).log(Level.INFO, "check args.length < 6!!!" );
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonSend;
    private JFileChooser jFileChooser1;
    private JLabel jLabelUserID;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenuBar jMenuBar1;
    private JMenuItem jMenuItemCopy;
    private JMenuItem jMenuItemExit;
    private JMenuItem jMenuItemPaste;
    private JMenuItem jMenuItemSave;
    private JScrollPane jScrollPane1;
    private JTextArea jTextAreaChatHistory;
    private JTextField jTextFieldMsg;
    private JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
